name: Build and publish 4.x-5.x
on:
  push:
    tags:
      - '*'
  release:
    types: [ created ]
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: TEST
      run: echo 3.x, 4.x, 4.x
    - name: Upload binaries to release 3.x
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: com_food-3.x.zip
        tag: dev
        overwrite: true
        file_glob: true
    - name: Upload binaries to release 4.x-5.x
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: com_food-4.x-5.x.zip
        tag: dev
        overwrite: true
        file_glob: true
