name: Build and publish 4.x-5.x
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Сборка проекта
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
    - uses: actions/checkout@v3
    - name: TEST
      run: echo 3.x, 4.x-5.x
    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    - name: Build 3.x, 4.x-5.x
        run: |
          npm run inst
          npm run build
    - name: Upload binaries to release 3.x
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: com_food-3.x.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Upload binaries to release 4.x-5.x
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: com_food-4.x-5.x.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
